### ISSUE TITLE
TypeScript issues with the Yjs dependency

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#1299]
I’ve submitted a PR to Nitro, and their build is failing because it’s seem to check the types of all dependencies (which we skip I think) and the build fails because of Yjs:

```
Error:  Error building /home/runner/work/nitro/nitro: SyntaxError: Unexpected token (1:14) in /home/runner/work/nitro/nitro/node_modules/.pnpm/@scalar+api-reference@1.20.7_postcss@8.4.38_typescript@5.4.3_unified@11.0.4_vue@3.4.21_yjs@13.6.14/node_modules/@scalar/api-reference/dist/components/ApiClientModal.vue.d.ts
Error:  Unexpected token (1:14) in /home/runner/work/nitro/nitro/node_modules/.pnpm/@scalar+api-reference@1.20.7_postcss@8.4.38_typescript@5.4.3_unified@11.0.4_vue@3.4.21_yjs@13.6.14/node_modules/@scalar/api-reference/dist/components/ApiClientModal.vue.d.ts
  at pp$4.raise (node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:21621:13)
  at pp$9.unexpected (node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:18829:8)
  at pp$9.expect (node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:18823:26)
  at pp$8.parseImportSpecifiers (node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:19955:12)
  at Parser.parseImport (node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:26126:32)
  at pp$8.parseStatement (node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:19005:49)
  at pp$8.parseTopLevel (node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:18886:21)
  at Parser.parse (node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:18658:15)
  at Function.parse (node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:18708:35)
  at Graph.contextParse (node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25754:38) 

Error:  Unexpected token (1:14) in /home/runner/work/nitro/nitro/node_modules/.pnpm/@scalar+api-reference@1.20.7_postcss@8.4.38_typescript@5.4.3_unified@11.0.4_vue@3.4.21_yjs@13.6.14/node_modules/@scalar/api-reference/dist/components/ApiClientModal.vue.d.ts
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

I can probably work around this for the PR, but our packages shouldn’t fail the TS check in other environments.

Can we do something to fix that? Or get rid of the Yjs dependencies? 🤔 And we should probably go back to type checking our dependencies again.

**Comment by marclave** [comment]
@hanspagel if we want to get rid of the yjs dependency we need to remove codemirror yjs.next out of this repo and pass it in from org (which we should do)

wdyt? I actually have a draft PR open for this :)

**Comment by hanspagel** [comment]
I think we did this already and intentionally moved it to the OSS repo! I think we’d all prefer to not have yjs shipped with the OSS package, but @geoffgscott probably knows whether we can work around this.

**Comment by marclave** [comment]
yeah sadly `y-codemirror.next` includes yjs, so we need to add that as a peer dep :)
