### ISSUE TITLE
`requestBody` with `anyOf` defined: no example is generated for the body

### ISSUE THREAD

**Issue by kevinand11** [scalar/scalar#2417]
### What happens?

<img width="1293" alt="Screenshot 2024-07-07 at 15 18 32" src="https://github.com/scalar/scalar/assets/48160414/ebde14c7-c42f-4d89-8e8d-3e854e320563">

### What did you expect to happen?

An example should be generated from the first schema in the `anyOf` array

### How can we reproduce the issue?

1. Go to [https://sandbox.scalar.com/e/Bj8Ak](https://sandbox.scalar.com/e/Bj8Ak)
2. Create a request where the schema body has the `anyOf` defined, even if it has just one item in the array
3. The body example is no more shown

### OpenAPI Document

https://sandbox.scalar.com/e/Bj8Ak

**Comment by kevinand11** [comment]
Looking at the console, I notice this error logged as well 

```
TypeError: Cannot read properties of undefined (reading 'trim')
    at Request.vue-BK6VCWpy.js:34:34802
    at hH.fn (index-C8l1rRol.js:10:9499)
    at hH.run (index-C8l1rRol.js:10:1605)
    at get value (index-C8l1rRol.js:10:9744)
    at setup (Request.vue-BK6VCWpy.js:34:34865)
    at Yg (index-C8l1rRol.js:14:38)
    at cbe (index-C8l1rRol.js:14:40539)
    at lbe (index-C8l1rRol.js:14:40318)
    at G (index-C8l1rRol.js:14:23675)
    at $ (index-C8l1rRol.js:14:23549)
```

**Comment by kevinand11** [comment]
@hanspagel  I created a PR that resolves this https://github.com/scalar/scalar/pull/3106. Would love to get some feedback
