### ISSUE TITLE
@scalar/api-reference v1.25.12 and v1.25.13 cause the UI to crash

### ISSUE THREAD

**Issue by subzero10** [scalar/scalar#3165]
### What happens?

I am using Scalar.AspNetCore. Since the release of 1.25.12 (yesterday), the UI is crashing with the following error:
```
Failed to fetch spec from URL: ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "array",
    "path": [
      "type"
    ],
    "message": "Expected string, received array"
  }
]
    at get error (standalone.js:18441:10)
    at w8.parse (standalone.js:18477:64)
    at standalone.js:19266:13
    at standalone.js:19264:54
    at Array.forEach (<anonymous>)
    at C6 (standalone.js:19264:29)
    at standalone.js:19373:36
    at Array.forEach (<anonymous>)
    at Y6 (standalone.js:19373:15)
    at async l (standalone.js:19537:61)
```
I traced it to the fact that we have GET requests with query parameters that are not plain strings - for example I have a query parameter that is mapped to a list of strings (List<string>).

Have you considered allowing the app to continue without crashing, even if Zod validation fails (at least for the production environment)? 

### What did you expect to happen?

The UI should not crash. I know that complex types as query parameters may not be supported out of the box, but even in that case it shouldn't break the whole tool.

**Comment by amritk** [comment]
Hey @subzero10 do you think you could pass me the spec if its public? Or just  mock one up with those parameters

**Comment by marclave** [comment]
@subzero10 

i tried to create a path parameter with an array type and it worked, if you can share a small snippet of your spec we can fix :) 

```
        "parameters": [
          {
            "name": "petId",
            "in": "path",
            "description": "ID of pet to update",
            "required": true,
            "schema": { "type": "array" }
          }
        ],
```

<img width="687" alt="image" src="https://github.com/user-attachments/assets/3ba4d608-ffe5-4b88-973a-6f0300b84c23">

**Comment by omarkhatibco** [comment]
Hi @amritk ,

I could share with you my api ui if thats helps, it's also broken on the latest version.

url: https://api.mando.cx/swagger#tag/auth

I'm using `@scalar/hono-api-reference v 0.5.147`

**Comment by marclave** [comment]
fixed in 1.25.17 :)

**Comment by subzero10** [comment]
Hey @marclave, 1.25.17 seems to have improved things - the UI does not crash anymore.
I get a bunch of warnings on Dev tools, but I guess that's expected.
Now I see another regression: the name of the query param is not shown for the query params that were _invalid_ (see screenshot), it just prints "Key". In previous versions (1.25.11), the query param name was there.

Here's a reproducible example:
```
  "paths": {
    "/api/operations-profile": {
      "post": {
        "tags": [
          "Operations Profile"
        ],
        "summary": "Create operations profile",
        "operationId": "CoreBankingSystemClientAccountManagementApiEndpointsOperationsProfileCreate",
        "requestBody": {
          "x-name": "CreateBasicResourceRequest",
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateBasicResourceRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BasicResourceResponseOfUlid"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Operations Profile"
        ],
        "summary": "Get operations profiles",
        "operationId": "CoreBankingSystemClientAccountManagementApiEndpointsOperationsProfileIndex",
        "parameters": [
          {
            "name": "include",
            "in": "query",
            "style": "form",
            "explode": true,
            "description": "Optional list of relationships to include in the response.",
            "schema": {
              "type": "array",
              "nullable": true,
              "items": {
                "type": "string"
              }
            }
          },
          {
            "name": "pageNumber",
            "in": "query",
            "required": true,
            "description": "Page number to retrieve.",
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 1
            }
          },
          {
            "name": "pageSize",
            "in": "query",
            "required": true,
            "description": "Page size.",
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 100
            }
          },
          {
            "name": "pageCursor",
            "in": "query",
            "description": "In the case of a cursor-based pagination, the cursor is used to determine the next page of results.\nIf this is used, the page number is ignored.",
            "schema": {
              "type": "string",
              "nullable": true
            }
          },
          {
            "name": "filter",
            "in": "query",
            "style": "form",
            "explode": true,
            "description": "Optional list of filters to apply to the query. ",
            "schema": {
              "type": "array",
              "nullable": true,
              "items": {
                "$ref": "#/components/schemas/FilterQuery"
              }
            }
          },
          {
            "name": "sort",
            "in": "query",
            "style": "form",
            "explode": true,
            "description": "Optional list of sort options to apply to the query.",
            "schema": {
              "type": "array",
              "nullable": true,
              "items": {
                "$ref": "#/components/schemas/SortQuery"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BaseGetListResultOfBasicResourceResponseOfUlid"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          }
        }
      }
    },
```

![CleanShot 2024-09-23 at 09 12 13@2x](https://github.com/user-attachments/assets/169f7d30-a490-419b-bb82-aa94bef70694)

**Comment by rakibdev** [comment]
Same issue. I have "enum" containing `null` value.

swagger.json

```json
"experienceType": {
  "type": "string",
  "enum": ["fresher", "junior", "mid", "senior", null],
  "nullable": true
},
```
UI not showing any enum.

![image](https://github.com/user-attachments/assets/eb9d14fd-9be5-483d-81a2-6388294f091b)

Console error

![image](https://github.com/user-attachments/assets/1c24d42a-30a7-44ad-aff9-3637a591ce2a)

Even though it's a valid schema according to the spec.

![image](https://github.com/user-attachments/assets/a8d562b0-91d8-49ea-804c-8657f56e9915)

**Comment by amritk** [comment]
Ah yes we need to add support for nullable!

**Comment by amritk** [comment]
Hi @rakibdev @subzero10 I am just going to merge this ticket into another one and you can follow the updates there!

https://github.com/scalar/scalar/issues/3450
