### ISSUE TITLE
`@scalar/fastify-api-reference` cannot handle IPv6 address (splits url wrongly)

### ISSUE THREAD

**Issue by David-van-der-Sluijs** [scalar/scalar#3645]
### What happens?

The `@scalar/fastify-api-reference` plugin does not seem to parse a IPv6 correctly.

I get the error:
```
TypeError: Invalid URL\n    at new URL (node:internal/url:806:29)\n    at Object.handler (node_modules/@scalar/fastify-api-reference/dist/index.js:14486:28)\n    at preHandlerCallbackInner (node_modules/fastify/lib/handleRequest.js:161:24)\n    at preHandlerCallback (node_modules/fastify/lib/handleRequest.js:129:5)\n    at validationCompleted (node_modules/fastify/lib/handleRequest.js:119:5)\n    at preValidationCallback (node_modules/fastify/lib/handleRequest.js:96:5)\n    at handler (node_modules/fastify/lib/handleRequest.js:73:7)\n    at Object.handleRequest (node_modules/fastify/lib/handleRequest.js:29:5)\n    at runPreParsing (node_modules/fastify/lib/route.js:570:19)\n    at Object.routeHandler [as handler] (node_modules/fastify/lib/route.js:490:7) {\n  code: 'ERR_INVALID_URL',\n  input: '/documentation/',\n  base: 'http://[fd00'\n}
```

Notice the last bit:
```
code: 'ERR_INVALID_URL',\n  input: '/documentation/',\n  base: 'http://[fd00'\n
```

I registered the plugin with:
```
routePrefix  : '/documentation',
```

And I reached the server via a private IPv6 address `http://[fd00:99::1:1]:8080`.

It seems like it cut the IPv6 address at the first `:` (probably to parse the port)

If I reach the server with a IPv4 address it works fine.

### What did you expect to happen?

To not error out.

**Comment by hanspagel** [comment]
I’m don’t remember doing anything with the host at all 🤔 Anyway, thanks for the report. We’ll investigate.

**Comment by David-van-der-Sluijs** [comment]
I located it must be somewhere around [here](https://github.com/scalar/scalar/blob/f93f74584e6d68ec5c3f391f8c3cc3c8a2ffa82d/packages/fastify-api-reference/src/fastifyApiReference.ts#L315).

**Comment by David-van-der-Sluijs** [comment]
I found that this is actually a problem with Fastify itself.

This simple server:
```
import {fastify} from 'fastify';

const server = fastify({
    logger: true
});

server.get('/', (request, reply) => {
    console.log('Hostname: "' + request.hostname + '"');
    reply.send('Hello World!');
});

server.listen({port: 3040}, (err, address) => {
    console.log(`Server listening at ${address}`);
});
```

Prints:
```
Server listening at http://[::1]:3040
{"level":30,"time":1730060215348,"pid":34830,"hostname":"<redacted>","reqId":"req-1","req":{"method":"GET","url":"/","host":"[::1]:3040","remoteAddress":"::1","remotePort":63860},"msg":"incoming request"}
Hostname: "["
```

We can see that the hostname resolved to `[` which is wrong. It should be `[::1]`.

**Comment by David-van-der-Sluijs** [comment]
I will report it to Fastify itself.
