### ISSUE TITLE
添加 Bearer 认证后 实例代码不工作了

### ISSUE THREAD

**Issue by LazyCoderSuhe** [scalar/scalar#3927]
### What happens?

![image](https://github.com/user-attachments/assets/be84b205-8422-4173-9c95-81d9170047b8)
![image](https://github.com/user-attachments/assets/d1a606b0-ad36-4855-a353-d3f90e5439e9)
就不工作了

### What did you expect to happen?

这个 如何解决 

### OpenAPI Document

no

**Comment by xC0dex** [comment]
This is how the authentication configuration section looks like:

```json
"authentication": {
  "http": {
    "bearer": {
       "token": "your-b"
      }
   }
}
```

The browser console contains the following error:

```console
TypeError: Cannot read properties of undefined (reading 'username')
    at Ys (standalone.js:1507:80)
    at standalone.js:19104:17
    at r (standalone.js:651:40)
    at wa (standalone.js:790:16)
    at Proxy.<anonymous> (standalone.js:19012:4)
    at Po (standalone.js:1162:56)
    at ht.s [as fn] (standalone.js:1040:51)
    at ht.run (standalone.js:392:48)
    at A (standalone.js:1046:50)
    at T (standalone.js:1016:46)
```

**Comment by LazyCoderSuhe** [comment]
我找到解决方案。发现不能单独配置 Bearer 需要配置Basic 他俩一期配置就可以出现提示语句了，
    options
        .WithPreferredScheme("Basic") // Security scheme name from the OpenAPI document
        .WithHttpBasicAuthentication(basic =>
        {
            basic.Username = "your-username";
            basic.Password = "your-password";
        });

    // Bearer
    options
        .WithPreferredScheme("Bearer") // Security scheme name from the OpenAPI document
        .WithHttpBearerAuthentication(bearer =>
        {
            bearer.Token = "your-bearer-token";
        });
![image](https://github.com/user-attachments/assets/17ef4e36-165b-47df-bd96-405ed8ced535)


但实例代码中 无法自动接入自动加入 认证信息

**Comment by maxstue** [comment]
I am getting the same error when setting the preferred scheme to "Bearer" and setting a token value.

**Comment by yuefengkai** [comment]
+1

**Comment by xC0dex** [comment]
@hanspagel we could add this bug to https://github.com/scalar/scalar/issues/3696

**Comment by cethink** [comment]
fixed?

**Comment by cethink** [comment]
v1.2.68 已修复

**Comment by xC0dex** [comment]
I'll close this issue as I cannot reproduce the behavior anymore 👍 It works as expected.
