### ISSUE TITLE
using the RangeAttribute to validate a ViewModel in a .NET Web API interface, documentation cannot be generated properly.

### ISSUE THREAD

**Issue by ynanech** [scalar/scalar#4123]
### What happens?

When using the RangeAttribute to validate a model property in a .NET 9 minimal API endpoint, documentation cannot be generated properly with Scalar.AspNetCore version 1.2.49. If the Range attribute is removed, the documentation generates correctly; however, including the Range attribute prevents proper documentation generation and results in console input errors. This is my API endpoint:
﻿
```
api.MapPut("{orderId:required:length(10,32)}/Ship", ShipAsync);

public static async Task<Results<Ok, ProblemHttpResult>> ShipAsync(
   [FromRoute] long orderId, [FromBody] ShipOrderRequestVm request, CancellationToken cancellationToken)
{
   return TypedResults.Ok();
}

public class ShipOrderRequestVm(long? addressId)
{
   [Range(999999999, long.MaxValue)]
   public long? AddressId { get; set; } = addressId;
}
```

The console prints the following error:"

```
2024-12-07T17:31:08       System.FormatException: The input string '9.223372036854776E+18' was not in a correct format.
2024-12-07T17:31:08          at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
2024-12-07T17:31:08          at System.Number.ParseDecimal[TChar](ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
2024-12-07T17:31:08          at System.Decimal.Parse(String s, IFormatProvider provider)
2024-12-07T17:31:08          at Microsoft.AspNetCore.OpenApi.JsonNodeSchemaExtensions.ApplyValidationAttributes(JsonNode schema, IEnumerable`1 validationAttributes)
2024-12-07T17:31:08          at Microsoft.AspNetCore.OpenApi.OpenApiSchemaService.<>c__DisplayClass0_0.<.ctor>b__2(JsonSchemaExporterContext context, JsonNode schema)
2024-12-07T17:31:08          at System.Text.Json.Schema.JsonSchema.<ToJsonNode>g__CompleteSchema|104_0(JsonNode schema, <>c__DisplayClass104_0&)
2024-12-07T17:31:08          at System.Text.Json.Schema.JsonSchema.ToJsonNode(JsonSchemaExporterOptions options)
2024-12-07T17:31:08          at System.Text.Json.Schema.JsonSchema.ToJsonNode(JsonSchemaExporterOptions options)
2024-12-07T17:31:08          at System.Text.Json.Schema.JsonSchemaExporter.GetJsonSchemaAsNode(JsonTypeInfo typeInfo, JsonSchemaExporterOptions exporterOptions)
2024-12-07T17:31:08          at System.Text.Json.Schema.JsonSchemaExporter.GetJsonSchemaAsNode(JsonSerializerOptions options, Type type, JsonSchemaExporterOptions exporterOptions)
2024-12-07T17:31:08          at Microsoft.AspNetCore.OpenApi.OpenApiSchemaService.CreateSchema(OpenApiSchemaKey key)
2024-12-07T17:31:08          at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
2024-12-07T17:31:08          at Microsoft.AspNetCore.OpenApi.OpenApiSchemaStore.GetOrAdd(OpenApiSchemaKey key, Func`2 valueFactory)
2024-12-07T17:31:08          at Microsoft.AspNetCore.OpenApi.OpenApiSchemaService.GetOrCreateSchemaAsync(Type type, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, ApiParameterDescription parameterDescription, Boolean captureSchemaByRef, CancellationToken cancellationToken)
2024-12-07T17:31:08          at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetJsonRequestBody(IList`1 supportedRequestFormats, ApiParameterDescription bodyParameter, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken)
2024-12-07T17:31:08          at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetRequestBodyAsync(ApiDescription description, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken)
2024-12-07T17:31:08          at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperationAsync(ApiDescription description, HashSet`1 capturedTags, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken)
2024-12-07T17:31:08          at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperationsAsync(IGrouping`2 descriptions, HashSet`1 capturedTags, IServiceProvider scopedServiceProvider, IOpenApiOperationTransformer[] operationTransformers, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken)
2024-12-07T17:31:08          at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiPathsAsync(HashSet`1 capturedTags, IServiceProvider scopedServiceProvider, IOpenApiOperationTransformer[] operationTransformers, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken)
2024-12-07T17:31:08          at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiDocumentAsync(IServiceProvider scopedServiceProvider, CancellationToken cancellationToken)
2024-12-07T17:31:08          at Microsoft.AspNetCore.Builder.OpenApiEndpointRouteBuilderExtensions.<>c__DisplayClass0_0.<<MapOpenApi>b__0>d.MoveNext()
2024-12-07T17:31:08       --- End of stack trace from previous location ---
2024-12-07T17:31:08          at Microsoft.AspNetCore.Http.Generated.<GeneratedRouteBuilderExtensions_g>F56B68D2B55B5B7B373BA2E4796D897848BC0F04A969B1AF6260183E8B9E0BAF2__GeneratedRouteBuilderExtensionsCore.<>c__DisplayClass2_0.<<MapGet0>g__RequestHandler|5>d.MoveNext()
2024-12-07T17:31:08       --- End of stack trace from previous location ---
2024-12-07T17:31:08          at Finbuckle.MultiTenant.AspNetCore.Internal.MultiTenantMiddleware.Invoke(HttpContext context)
2024-12-07T17:31:08          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)

```

**Comment by xC0dex** [comment]
Hey @ynanech,

The issue does not lie in the `Scalar.AspNetCore` package but in the OpenAPI document generator in `Microsoft.AspNetCore.OpenApi`. I recommend reporting this bug in the [AspNetCore repository](https://github.com/dotnet/aspnetcore).

**Comment by xC0dex** [comment]
**Update:** It's already reported https://github.com/dotnet/aspnetcore/issues/57390. I'll close this issue.
