### ISSUE TITLE
nuxt: 500 localStorage is not defined

### ISSUE THREAD

**Issue by mirsella** [scalar/scalar#4205]
### What happens?

hello !

```
500

localStorage is not defined

at setup (./node_modules/.pnpm/@scalar+api-reference@1.25.82_@hyperjump+browser@1.1.6_change-case@5.4.4_tailwindcss@3.4.16_typescript@5.6.2/node_modules/@scalar/api-reference/dist/components/ApiReferenceLayout.js2.js:117:15)
at callWithErrorHandling (./node_modules/.pnpm/@vue+runtime-core@3.5.13/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:200:19)
at setupStatefulComponent (./node_modules/.pnpm/@vue+runtime-core@3.5.13/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7848:25)
at setupComponent (./node_modules/.pnpm/@vue+runtime-core@3.5.13/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7809:36)
at renderComponentVNode (./node_modules/.pnpm/@vue+server-renderer@3.5.13_vue@3.5.13_typescript@5.6.2_/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:645:15)
at renderVNode (./node_modules/.pnpm/@vue+server-renderer@3.5.13_vue@3.5.13_typescript@5.6.2_/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:779:14)
at renderComponentSubTree (./node_modules/.pnpm/@vue+server-renderer@3.5.13_vue@3.5.13_typescript@5.6.2_/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:730:7)
at renderComponentVNode (./node_modules/.pnpm/@vue+server-renderer@3.5.13_vue@3.5.13_typescript@5.6.2_/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:664:12)
at Module.ssrRenderComponent (./node_modules/.pnpm/@vue+server-renderer@3.5.13_vue@3.5.13_typescript@5.6.2_/node_modules/@vue/server-re
```

thanks

### What did you expect to happen?

work

**Comment by amritk** [comment]
This one should be fixed! Feel free to re-open if it persists 🙂
